---
- name: Install image_resizer package
  pip:
      name: git+https://github.com/wiating-app/image_resizer.git
      state: forcereinstall
      virtualenv: /opt/wiating/venvs/image_resizer
      virtualenv_python: python3
