---
- name: Copy package files
  copy:
      src: files/image_resizer
      dest: /opt/wiating

- name: Install image_resizer package
  pip:
      name: file:///opt/wiating/image_resizer
      virtualenv: /opt/wiating/venvs/image_resizer
      virtualenv_python: python3
