---
- name: Copy package files
  copy:
      src: files/image_resizer
      dest: /opt

- name: Install image_resizer package
  pip:
      name: file:///opt/image_resizer
      virtualenv: /opt/venvs/image_resizer
      virtualenv_python: python3
