---
- name: Increase single body size
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'client_max_body_size'
    insertafter: '^http {'
    line: '    client_max_body_size 10m;'

- name: Copy site config
  copy:
      src: files/default
      dest: /etc/nginx/conf.d/default.conf
      force: yes
