---
- name: Create a directory if it does not exist
  file:
    path: /opt/wiating
    state: directory
    mode: '0750'
    owner: admin
    group: admin
  become: yes

- name: Copy package files
  copy:
      src: files/rabbit_queue
      dest: /opt/wiating

- name: Install rabbit_queue package for wiating backend
  pip:
      name: file:///opt/wiating/rabbit_queue
      virtualenv: /opt/wiating/venvs/wiating_backend
      virtualenv_python: python3

- name: Install rabbit_queue package for image resizer
  pip:
      name: file:///opt/wiating/rabbit_queue
      virtualenv: /opt/wiating/venvs/image_resizer
      virtualenv_python: python3
