---
- name: Put elasticsearch index mapping
  uri:
    url: http://localhost:9200/wiaty
    method: PUT
    body: "{{ lookup('file','mapping.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: [200, 400]
