---
- name: Install dependencies
  apt:
      name: ['build-essential', 'python-dev', 'python3-setuptools']
      state: latest
  become: yes

- name: Install uWSGI
  pip:
      name: uwsgi
      executable: pip3
  become: yes
