---
- hosts: all
  roles:
      - role: tools
      - role: python
      - role: geerlingguy.rabbitmq
        become: yes
      - role: nginxinc.nginx
        become: yes
      - role: nginx_config
      - role: rabbit_queue
      - role: wiating_backend
      - role: image_resizer
      - role: uwsgi
